version: 2.1
orbs:
  orb-tools-alpha: {}

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      - orb-tools-alpha/lint:
          filters: *filters
      - orb-tools-alpha/pack:
          filters: *filters
      - orb-tools-alpha/review:
          orb_name: orb-tools
          filters: *filters
      - orb-tools-alpha/publish:
          name: publish_dev_test
          orb_name: circleci/orb-tools
          vcs_type: <<pipeline.project.type>>
          pub_type: dev
          github_token: GHI_TOKEN
          requires:
            [orb-tools-alpha/lint, orb-tools-alpha/review, orb-tools-alpha/pack]
          context: orb-publisher
      - orb-tools-alpha/publish:
          orb_name: circleci/orb-tools
          vcs_type: <<pipeline.project.type>>
          pub_type: production
          requires:
            [orb-tools-alpha/lint, orb-tools-alpha/review, orb-tools-alpha/pack, publish_dev_test]
          context: orb-publisher
          github_token: GHI_TOKEN
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
