version: 2.1
orbs:
  orb-tools-alpha: {}
workflows:
  test-deploy:
    jobs:
      - orb-tools-alpha/lint:
          filters:
            tags:
              only: /.*/
      - orb-tools-alpha/pack:
          filters:
            tags:
              only: /.*/
      - orb-tools-alpha/review:
          filters:
            tags:
              only: /.*/
      - orb-tools-alpha/publish:
          orb_name: circleci/orb-tools
          vcs_type: <<pipeline.project.type>>
          pub_type: production
          requires:
            [orb-tools-alpha/lint, orb-tools-alpha/review, orb-tools-alpha/pack]
          context: orb-publisher
          github_token: GHI_TOKEN
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
