description: >
  Sets mandatory git config fields to allow creating and pushing of tags.
  If not set it will default to details from the VCS system, composed from the $CIRCLE_USERNAME variable.
  If both parameters are set, they will be used instead.

parameters:
  user-name:
    description: >
      Override git user name.
    type: string
    default: ""

  user-email:
    description: >
      Override git user email.
    type: string
    default: ""

steps:
  - run:
      name: git config
      environment:
        GIT_USER_NAME: << parameters.user-name >>
        GIT_EMAIL: << parameters.user-email >>
      command: <<include(scripts/configure-git.sh)>>
